# Generated by Django 5.2 on 2025-04-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
        migrations.AddField(
            model_name="client",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="client",
            name="title",
            field=models.CharField(default=1, max_length=255, verbose_name="title"),
            preserve_default=False,
        ),
    ]
