# Generated by Django 5.2 on 2025-04-17 13:44

import utils.secrets
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0002_alter_client_options_client_description_client_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_id",
            field=models.CharField(
                default=utils.secrets.generate_client_id, max_length=16, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_secret",
            field=models.CharField(
                default=utils.secrets.generate_client_secret, max_length=64
            ),
        ),
    ]
