# Generated by Django 5.2 on 2025-04-15 13:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0002_alter_userprivacysettings_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notofication",
            new_name="Notification",
        ),
    ]
