# Generated by Django 5.2 on 2025-04-15 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_securityquestion_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emergencydetails",
            options={
                "verbose_name": "Emergency Details",
                "verbose_name_plural": "Emergency Details",
            },
        ),
        migrations.AlterUniqueTogether(
            name="emergencydetails",
            unique_together={("user", "relationship")},
        ),
    ]
