# Generated by Django 5.2 on 2025-04-15 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_emergencydetails_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emergencydetails",
            unique_together=set(),
        ),
    ]
